[target.aarch64-linux-android]
ar = "/usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar"
linker = "/usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang"

[target.arm-unknown-linux-gnueabihf]
ar = "/home/runner/arm-rpi-linux-gnueabihf/bin/arm-rpi-linux-gnueabihf-ar"
linker = "/home/runner/arm-rpi-linux-gnueabihf/bin/arm-rpi-linux-gnueabihf-gcc"
