name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Configure Rust for Android
        run: |
          cp cargo-config.toml ~/.cargo/config
          rustup target add aarch64-linux-android

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target aarch64-linux-android --release

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/libraptorq.a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
