name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: |
          rustup default beta
          cargo build --release

      - name: Hack to fix duplicate symbol (badness 10000)
        run: |
          mkdir extracted
          cd extracted
          ar -x ../target/release/libraptorq.a
          $(brew --prefix llvm@15)/bin/llvm-objcopy --redefine-sym=_rust_eh_personality=_rust_canadian_personality $(find . -name 'raptorq-*')
          libtool -static -o ../libraptorq-macos12.a *.o

      - name: Prepare output
        run: |
          cd include
          zip -r ../include.zip .

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos12
          path: |
            include.zip
            libraptorq-macos12.a
            LICENSE

  build-macos-arm64:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: |
          rustup default beta
          cargo build --release

      - name: Hack to fix duplicate symbol (badness 10000)
        run: |
          mkdir extracted
          cd extracted
          ar -x ../target/release/libraptorq.a
          $(brew --prefix llvm@15)/bin/llvm-objcopy --redefine-sym=_rust_eh_personality=_rust_canadian_personality $(find . -name 'raptorq-*')
          libtool -static -o ../libraptorq-macos-arm64.a *.o

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos-arm64
          path: libraptorq-macos-arm64.a

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get RPi toolchain
        run: |
          wget https://github.com/sfjohnson/rpi-toolchain/releases/download/v0.1.8/aarch64-rpi4-linux-gnu.tar.xz
          tar xf aarch64-rpi4-linux-gnu.tar.xz -C ~

      - name: Configure Rust for RPi
        run: |
          rustup default beta
          cp cargo-config.toml ~/.cargo/config
          rustup target add aarch64-unknown-linux-gnu

      - name: Build RPi
        run: cargo build --target aarch64-unknown-linux-gnu --release
        env:
          TARGET_CC: /home/runner/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu-gcc
          TARGET_AR: /home/runner/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu-ar

      - name: Build linux-x64
        run: cargo build --release

      - name: Hack to fix duplicate symbol (badness 10000)
        run: |
          mkdir extracted1
          cd extracted1
          $TARGET_AR -x ../target/aarch64-unknown-linux-gnu/release/libraptorq.a
          $TARGET_OBJCOPY --redefine-sym=rust_eh_personality=rust_canadian_personality $(find . -name 'raptorq-*')
          $TARGET_AR cqT libraptorq.a $(find . -name '*.o' | tr '\n' ' ')
          echo -e 'create libraptorq.a\naddlib libraptorq.a\nsave\nend' | $TARGET_AR -M
          mv libraptorq.a ../libraptorq-rpi-arm64.a
          mkdir ../extracted2
          cd ../extracted2
          ar -x ../target/release/libraptorq.a
          objcopy --redefine-sym=rust_eh_personality=rust_canadian_personality $(find . -name 'raptorq-*')
          ar cqT libraptorq.a $(find . -name '*.o' | tr '\n' ' ')
          echo -e 'create libraptorq.a\naddlib libraptorq.a\nsave\nend' | ar -M
          mv libraptorq.a ../libraptorq-linux-x64.a
        env:
          TARGET_AR: /home/runner/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu-ar
          TARGET_OBJCOPY: /home/runner/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu-objcopy

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-linux
          path: |
            libraptorq-rpi-arm64.a
            libraptorq-linux-x64.a

  create-release:
    runs-on: ubuntu-22.04
    needs: [build-macos, build-macos-arm64, build-linux]
    steps:
      - name: Get build output macos12
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos12

      - name: Get build output macos-arm64
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos-arm64

      - name: Get build output linux
        uses: actions/download-artifact@v4
        with:
          name: build-output-linux

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            include.zip
            libraptorq-macos12.a
            libraptorq-macos-arm64.a
            libraptorq-rpi-arm64.a
            libraptorq-linux-x64.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
